#ifndef FILTER_PARAMETER_H
#define FILTER_PARAMETER_H

enum FilterParameter {
  FILTER_PARAMETER_FOREGROUND,
  FILTER_PARAMETER_HUE,
  FILTER_PARAMETER_INTENSITY,
  FILTER_PARAMETER_SATURATION,
  FILTER_PARAMETER_VALUE,
  NUM_FILTER_PARAMETERS
};

#endif // FILTER_PARAMETER_H
