#!/usr/bin/bash

export FROMQCH="$HOME/engauge6/bin/documentation/engauge.qch"
export FROMQHC="$HOME/engauge6/bin/documentation/engauge.qhc"
export FROMICO="$HOME/engauge6/src/img/digitizer.ico"
export FROMDLL="/C/QtOpenSource/Qt5.5.1/5.5/mingw492_32/bin"

ls -ls $FROMQCH | awk '{print $7,$8,$9,$10}'
ls -ls $FROMQHC | awk '{print $7,$8,$9,$10}'

read -p 'If the help input files are up to date, press Enter to continue'

echo "***Copying help input files"
mkdir -p documentation
cp $FROMQCH  ../bin/documentation
cp $FROMQHC  ../bin/documentation

echo "***Copying DLL libraries from $FROMDLL"
cp $FROMDLL/libwinpthread-1.dll ../bin/

echo "***Copying icon file"
cp $FROMICO  ../bin

# Notes:
# 1) Need gcc 4 at /C/cygwin/bin rather than gcc 3 at /usr/bin to prevent 'unrecognized command line
#    option -fno-keep-inline-dllexport'
# 2) Running 'make -j 4' exhausts system resources which hangs the build
# 3) windeployqt builds the release files in the same directory as the executable
export PATH=/C/QtOpenSource/Qt5.5.1/Tools/mingw492_32/bin:$PATH &&
echo "***Rebuilding release executable" &&
cd ../src &&
qmake engauge.pro &&
make clean &&
make &&
cd ../windows &&
echo "***Rebuilding release directory" &&
windeployqt -release ../bin/engauge.exe &&
echo "***Compiling release files" &&
candle.exe engauge.wxs &&
candle.exe WixUI_InstallDir_NoLicense.wxs &&
echo "***Creating MSI" &&
light.exe -ext WixUIExtension -ext WixUtilExtension engauge.wixobj WixUI_InstallDir_NoLicense.wixobj -o digit-exe-windows-64-bit-installer-6_0.msi
