#!/usr/bin/bash

# Notes:
# 1) Need gcc 4 at /C/cygwin/bin rather than gcc 3 at /usr/bin to prevent 'unrecognized command line
#    option -fno-keep-inline-dllexport'
# 2) Running 'make -j 4' exhausts system resources which hangs the build
# 3) windeployqt builds the release files in the same directory as the executable
export PATH=/C/MinGW/bin:$PATH &&
echo "***Rebuilding release executable" &&
cd ../src &&
qmake engauge.pro &&
make clean &&
make &&
cd ../windows &&
echo "***Rebuilding release directory" &&
windeployqt -release ../bin/engauge.exe &&
echo "***Compiling release files" &&
candle.exe engauge.wxs &&
echo "***Creating MSI" &&
light.exe engauge.wixobj
