#ifndef EXPORT_POINTS_SELECTION_RELATIONS_H
#define EXPORT_POINTS_SELECTION_RELATIONS_H

enum ExportPointsSelectionRelations {
  EXPORT_POINTS_SELECTION_RELATIONS_INTERPOLATE,
  EXPORT_POINTS_SELECTION_RELATIONS_RAW
};

#endif // EXPORT_POINTS_SELECTION_RELATIONS_H
