/******************************************************************************************************
 * (C) 2019 markummitchell@github.com. This file is part of Engauge Digitizer, which is released      *
 * under GNU General Public License version 2 (GPLv2) or (at your option) any later version. See file *
 * LICENSE or go to gnu.org/licenses for details. Distribution requires prior written permission.     *
 ******************************************************************************************************/

#ifndef GUIDELINE_STATE_H
#define GUIDELINE_STATE_H

/// Set of possible Guideline states. See class Guideline for more information
enum GuidelineState {
  GUIDELINE_STATE_DEPLOYED_CONSTANT_R_ACTIVE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_R_HIDE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_R_HOVER,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_R_LOCKED,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_T_ACTIVE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_T_HIDE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_T_HOVER,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_T_LOCKED,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_X_ACTIVE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_X_HIDE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_X_HOVER,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_X_LOCKED,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_Y_ACTIVE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_Y_HIDE,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_Y_HOVER,
  GUIDELINE_STATE_DEPLOYED_CONSTANT_Y_LOCKED,
  GUIDELINE_STATE_DISCARDED,  
  GUIDELINE_STATE_HANDLE,
  GUIDELINE_STATE_TEMPLATE_HORIZONTAL_BOTTOM_HIDE,
  GUIDELINE_STATE_TEMPLATE_HORIZONTAL_BOTTOM_HOVER,
  GUIDELINE_STATE_TEMPLATE_HORIZONTAL_BOTTOM_LURKING,  
  GUIDELINE_STATE_TEMPLATE_HORIZONTAL_TOP_HIDE,
  GUIDELINE_STATE_TEMPLATE_HORIZONTAL_TOP_HOVER,
  GUIDELINE_STATE_TEMPLATE_HORIZONTAL_TOP_LURKING,  
  GUIDELINE_STATE_TEMPLATE_VERTICAL_LEFT_HIDE,
  GUIDELINE_STATE_TEMPLATE_VERTICAL_LEFT_HOVER,
  GUIDELINE_STATE_TEMPLATE_VERTICAL_LEFT_LURKING,  
  GUIDELINE_STATE_TEMPLATE_VERTICAL_RIGHT_HIDE,
  GUIDELINE_STATE_TEMPLATE_VERTICAL_RIGHT_HOVER,
  GUIDELINE_STATE_TEMPLATE_VERTICAL_RIGHT_LURKING,  
  NUM_GUIDELINE_STATES
};

#endif // GUIDELINE_STATE_H
