#ifndef POINT_SHAPE_H
#define POINT_SHAPE_H

enum PointShape {
  POINT_SHAPE_CIRCLE,
  POINT_SHAPE_CROSS,
  POINT_SHAPE_DIAMOND,
  POINT_SHAPE_SQUARE,
  POINT_SHAPE_TRIANGLE,
  POINT_SHAPE_X
};

#endif // POINT_SHAPE_H
