#ifndef DOCUMENT_AXES_POINTS_REQUIRED_H
#define DOCUMENT_AXES_POINTS_REQUIRED_H

enum DocumentAxesPointsRequired {
  DOCUMENT_AXES_POINTS_REQUIRED_3,
  DOCUMENT_AXES_POINTS_REQUIRED_4
};

#endif // DOCUMENT_AXES_POINTS_REQUIRED_H
