#!/usr/bin/bash

rm -rf build 2>/dev/null
mkdir build

cd ../../
zip -r dev/cygport/build/local.zip . -x '*bin*' '*dev*' '*.git*' '*src/.moc*' '*src/.objs*' '*src/.rcc*'
cd dev/cygport/build

dos2unix ../engauge.cygport

sed 's/SRC_URI="${SRC_URI_REMOTE}"/SRC_URI="${SRC_URI_LOCAL}"/' ../engauge.cygport >/tmp/engauge.cygport

cygport /tmp/engauge.cygport download 
cygport /tmp/engauge.cygport prep 
cygport /tmp/engauge.cygport compile 
