#ifndef ZOOM_CONTROL_H
#define ZOOM_CONTROL_H

enum ZoomControl {
  ZOOM_CONTROL_MENU_ONLY,
  ZOOM_CONTROL_MENU_WHEEL,
  ZOOM_CONTROL_MENU_PLUSMINUS,
  ZOOM_CONTROL_MENU_WHEEL_PLUSMINUS
};

#endif // ZOOM_CONTROL_H
