#ifndef FILE_CMD_SERIALIZE_H
#define FILE_CMD_SERIALIZE_H

#include <QString>

extern const QString FILE_CMD_SERIALIZE_CMD;
extern const QString FILE_CMD_SERIALIZE_CMD_FILE_CLOSE;
extern const QString FILE_CMD_SERIALIZE_CMD_FILE_EXPORT;
extern const QString FILE_CMD_SERIALIZE_CMD_FILE_IMPORT;
extern const QString FILE_CMD_SERIALIZE_CMD_FILE_OPEN;
extern const QString FILE_CMD_SERIALIZE_CMD_TYPE;
extern const QString FILE_CMD_SERIALIZE_FILENAME;

#endif // FILE_CMD_SERIALIZE_H
