#!/bin/bash

# Test names. Synchronize with edit_one_test
tests=(TestGraphCoords TestProjectedPoint TestSpline)
if [ -n "$1" ]
then 
    tests=("$1");
fi

# Logging
LOGFILE="build_and_run_all_tests.log"
rm -rf $LOGFILE
echo "Afterwards, check $LOGFILE to verify success"

# Cleanup. We do not want to force complete rebuild for each test application since that takes VERY long
rm .moc_test/* 2>/dev/null
rm .obj_test/* 2>/dev/null
rm ../bin/Test* 2>/dev/null

# Make sure correct qt installation is being used, by looking for '5.' in the version number
VERSION5=`qmake -v | grep '5\.'`
if [ -z "$VERSION5" ]
then
    echo "Need Qt5";
else

    # Exit immediately on first error
    set -e 

    # Build tests
    for t in "${tests[@]}"
    do
	sed "s/TEST/$t/g" engauge_test_template.pro >engauge_test.pro
	qmake engauge_test.pro
        make clean 2>>$LOGFILE >/dev/null
	make all 2>>$LOGFILE >/dev/null
        rm engauge_test.pro
    done

    # Run tests
    for t in "${tests[@]}"
    do
	../bin/$t
    done
fi
