#!/bin/bash

# Test names. Synchronize with build_and_run_all_tests
tests=("TestGraphCoords" "TestSpline")

function edittest {
    sed "s/TEST/$1/g" engauge_test_template.pro >engauge_test.pro
    qtcreator engauge_test.pro
}

# Make sure correct qt installation is being used, by looking for '5.' in the version number
VERSION5=`qmake -v | grep '5\.'`
if [ -z "$VERSION5" ]
then
    echo "Need Qt5";
else

    for ((i = 0; i < ${#tests[@]}; i++))
    do
        echo "$i. ${tests[$i]}"
    done

    while true; do
        read -p "Which test? " index
        case $index in
            ''|*[!0-9]*) echo "Please choose a number";;
            *) if [ $index -lt ${#tests[@]} ]; then edittest ${tests[$index]}; exit; fi;;
        esac
    done
fi

