#ifndef AXES_HIGHLIGHT_H
#define AXES_HIGHLIGHT_H

/// Options for axes highlight.
enum AxesHighlight
{
  AXES_HIGHLIGHT_NONE,
  AXES_HIGHLIGHT_2_SECONDS,
  AXES_HIGHLIGHT_10_SECONDS,
  AXES_HIGHLIGHT_FOREVER
};

#endif // AXES_HIGHLIGHT_H
