#ifndef THETA_UNITS_H
#define THETA_UNITS_H

enum ThetaUnits {
  THETA_UNITS_DEGREES,
  THETA_UNITS_DEGREES_MINUTES,
  THETA_UNITS_DEGREES_MINUTES_SECONDS,
  THETA_UNITS_GRADIANS,
  THETA_UNITS_RADIANS,
  THETA_UNITS_TURNS
};

#endif // THETA_UNITS_H
