#ifndef COORD_UNITS_NON_POLAR_THETA_H
#define COORD_UNITS_NON_POLAR_THETA_H

#include <QString>

enum CoordUnitsDate {
  COORD_UNITS_DATE_SKIP,
  COORD_UNITS_DATE_MONTH_DAY_YEAR,
  COORD_UNITS_DATE_DAY_MONTH_YEAR,
  COORD_UNITS_DATE_YEAR_MONTH_DAY
};

enum CoordUnitsTime {
  COORD_UNITS_TIME_SKIP,
  COORD_UNITS_TIME_HOUR_MINUTE,
  COORD_UNITS_TIME_HOUR_MINUTE_SECOND,
  COORD_UNITS_TIME_HOUR_MINUTE_PM,
  COORD_UNITS_TIME_HOUR_MINUTE_SECOND_PM
};

enum CoordUnitsNonPolarTheta {
  COORD_UNITS_NON_POLAR_THETA_NUMBER,
  COORD_UNITS_NON_POLAR_THETA_DEGREES_MINUTES_SECONDS,
  COORD_UNITS_NON_POLAR_THETA_DATE_TIME
};

extern QString coordUnitsDateToString (CoordUnitsDate coordUnits);
extern QString coordUnitsTimeToString (CoordUnitsTime coordUnits);
extern QString coordUnitsNonPolarThetaToString (CoordUnitsNonPolarTheta coordUnits);

#endif // COORD_UNITS_NON_POLAR_THETA_H
